name: Rust Clippy & Audit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  audit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run clippy
      run: cargo clippy --verbose --all-targets --all-features -- -D warnings
    - name: Install cargo audit
      uses: taiki-e/install-action@cargo-audit
    - name: Run audit
      run: cargo audit
