name: Raspberry Pi 5 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: [self-hosted, linux, arm64]

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --all-targets
    - name: Run tests with hashbrown
      run: cargo test --all-targets --features "hashbrown"