name: Rust CI ARM64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Cache cargo bin
      uses: actions/cache@v5
      with:
        path: ~/.cargo/bin
        key: cargo-bin-stable-arm64
    
    - name: Install cargo-nextest
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo nextest run
    - name: Run tests with all features
      run: cargo nextest run --all-features
    - name: Run doc-tests with all features
      run: cargo test --doc --all-features