name: wasm ci

on:
  push:
    branches: [ "main", "feat_*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER: wasm-bindgen-test-runner

jobs:
  test-wasm:

    runs-on: [self-hosted, linux, x64]
    #runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install stable rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: wasm32-unknown-unknown
    - name: Install wasm-bindgen-cli
      uses: taiki-e/install-action@v2
      with:
        tool: wasm-bindgen-cli
    - name: Run tests
      run: cargo test --target wasm32-unknown-unknown --all