name: wasm

on:
  push:
    branches: [ "main", "feat_wasm" ]
  pull_request:
    branches: [ "main", "feat_wasm" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test-wasm:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - run: cargo test
    - run: wasm-pack test --headless --chrome
    - run: wasm-pack test --headless --firefox
    - run: wasm-pack test --headless --node